### ISSUE TITLE
AADSTS65001: The user or administrator has not consented to use the application

### ISSUE THREAD

**Issue by RobDaPraia** [Azure-Samples/active-directory-dotnet-native-multitarget#10]
Thanks for this sample.

Followed the guide and create app in Azure with Client ID and set Permissions.

However, after login, I don't a consent page asking for permissions, but instead get an error:

```
AADSTS65001: The user or administrator has not consented to use the application with ID '***'.  
              Send an interactive authorization request for this user and resource.\r\n
```
Don't know what to do, also set all possible permissions in the Azure portal to be sure not missing a privilege, see screenshot, but still no luck, same error message. 

Using Microsoft.IdentityModel.Clients.ActiveDirectory 3.9.302261508-alpha\

![permissions](https://cloud.githubusercontent.com/assets/3207395/14935925/3d1b12d4-0ee3-11e6-9cce-1757bffed6c2.jpg)

**Comment by RobDaPraia** [comment]
Resolved this by using tenant name in commonAuthority, for example:

   public static string commonAuthority = "https://login.windows.net/MydomainName.onmicrosoft.com";

**Comment by Samaludheen** [comment]
Hi,
RobDaPraia Thank you,,,you saved my life.

**Comment by tranthong90** [comment]
Hi RobDaPraia

Can you be more specific on where to put this code?
public static string commonAuthority = "https://login.windows.net/MydomainName.onmicrosoft.com";

**Comment by RobDaPraia** [comment]
Do a search in the solution for 'commonAuthority' and you find the class DirectorySearcher

```
namespace DirectorySearcherLib
{   
 public static class DirectorySearcher
    {
        public static string clientId = "f4f32287-2571-4edb-a534-661a0e91f55a";

        // Don't use 'common' authority it will crash on AADSTS65001: The user or administrator has not consented to use the application 
        // public static string commonAuthority = "https://login.windows.net/common";
        public static string commonAuthority = "https://login.windows.net/Mydomain.onmicrosoft.com";
```

**Comment by RobDaPraia** [comment]
Do a search in the solution for 'commonAuthority' and you find the class DirectorySearcher

```
namespace DirectorySearcherLib
{   
 public static class DirectorySearcher
    {
        public static string clientId = "**-*-*-**";

        // Don't use 'common' authority it will crash on AADSTS65001: The user or administrator has not consented to use the application 
        // public static string commonAuthority = "https://login.windows.net/common";
        public static string commonAuthority = "https://login.windows.net/Mydomain.onmicrosoft.com";
...
```

**Comment by MatthewAnthonyBordas** [comment]
@RobDaPraia YOU ARE A LIFESAVER THANK YOU SO MUCH OH MY GOD I LOVE YOU
