### ISSUE TITLE
Xamarin IOS sample does not work with linker set to "Link All"

### ISSUE THREAD

**Issue by jorgenstorlie** [Azure-Samples/active-directory-dotnet-native-multitarget#13]
I want to link all assemblies , but it does not work

I got this error:

The type initializer for 'Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext' threw an exception.

Is it any workaround or fix for this?

**Comment by jmprieur** [comment]
This is now fixed (in ADAL.NET).
The WebProxyProvider in the plaform specific code needed to be marked with an attribute to prevent it from being removed during the build when the Link all assemblies was chosen (See [here](https://developer.xamarin.com/guides/android/advanced_topics/linking/) for more info)
