### ISSUE TITLE
Error: 'User canceled Authentication' when running Universal Client

### ISSUE THREAD

**Issue by mores** [Azure-Samples/active-directory-dotnet-native-multitarget#17]
authResult = await authContext.AcquireTokenAsync(graphResourceUri, clientId, returnUri, parent);

Stack Trace
"   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenInteractiveHandler.VerifyAuthorizationResult()\r\n   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenInteractiveHandler.<PreTokenRequest>d__10.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<RunAsync>d__57.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenCommonAsync>d__39.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenAsync>d__28.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at DirectorySearcherLib.DirectorySearcher.<SearchByAlias>d__5.MoveNext()"

Is this related to: https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/684

**Comment by jmprieur** [comment]
@mores : thanks for helping us for narrowing down.

Can you please tell us a bit more about it?
- Which version of ADAL.Net? (did you use the sample straight as is?)
- did you try to sign-in with a corporate accounts? or a Microsoft personal account?
- if it's a corporate account, did you tenant admin apply conditional access policies (demanding Multi factor authentication for instance).

What are the steps to get to this exception?

cc: @jennyf19

**Comment by mores** [comment]
Yes, I used the sample straight from git.
I was never prompted with a sign-in page.

**Comment by jmprieur** [comment]
@mores, which version of UWP are you targeting?

**Comment by mores** [comment]
@jmprieur,  how can I tell ?

**Comment by jmprieur** [comment]
@more, if you right click on the DirSearchClient-Universal (Universal Windows).csproj in the solution explorer, and ask for the project properties, in the **Application** tab, this is the **Target version**
![image](https://user-images.githubusercontent.com/13203188/35808163-38f6dad6-0a85-11e8-97b8-04a23f98af2d.png)

**Comment by mores** [comment]
Target version: 10.0; Build 14393
Min version: 10,.0 Build 10240

**Comment by jmprieur** [comment]
Thanks @mores 
Would it be a sample that you used more than 90 days ago? and then came back recently?
Would be in this case: https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/958 (you might want to check with fiddler

**Comment by mores** [comment]
@jmprieur, Nope. I checked it out and ran it on the same day. Is there any way to turn up more verbose logging to see what is going on ?

**Comment by jmprieur** [comment]
There are 2 ways. 
- Add logging: See https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Logging-in-ADAL.Net
- User fiddler to see the details of the message returned by Azure AD

**Comment by mores** [comment]
@jmprieur, I added logging, see: https://github.com/mores/active-directory-dotnet-native-multitarget/tree/ISSUE-17

And this showed up in the log:
LOG: 2018-02-05T20:00:05.7812487Z: aed98b20-f67d-4585-a0f5-c61ccd20c908 - LoggerBase.cs: ADAL PCL.WinRT with assembly version '3.18.0.2306', file version '3.18.50123.1943' and informational version '2b4dc54f7c7d624467d6d588d6fa694f9a3fcdcf' is running...
LOG: 2018-02-05T20:00:05.7862633Z: aed98b20-f67d-4585-a0f5-c61ccd20c908 - LoggerBase.cs: ADAL PCL.WinRT with assembly version '3.18.0.2306', file version '3.18.50123.1943' and informational version '2b4dc54f7c7d624467d6d588d6fa694f9a3fcdcf' is running...
LOG: 2018-02-05T20:00:05.7942819Z: aed98b20-f67d-4585-a0f5-c61ccd20c908 - LoggerBase.cs: === Token Acquisition started: 
LOG: 2018-02-05T20:00:05.7962865Z: aed98b20-f67d-4585-a0f5-c61ccd20c908 - LoggerBase.cs: === Token Acquisition started:
LOG: 2018-02-05T20:00:06.5033597Z: aed98b20-f67d-4585-a0f5-c61ccd20c908 - LoggerBase.cs: Loading from cache.
LOG: 2018-02-05T20:00:06.5073569Z: aed98b20-f67d-4585-a0f5-c61ccd20c908 - LoggerBase.cs: Loading from cache.
LOG: 2018-02-05T20:00:06.5183713Z: aed98b20-f67d-4585-a0f5-c61ccd20c908 - LoggerBase.cs: Looking up cache for a token...
LOG: 2018-02-05T20:00:06.5213797Z: aed98b20-f67d-4585-a0f5-c61ccd20c908 - LoggerBase.cs: Looking up cache for a token...
LOG: 2018-02-05T20:00:06.5304354Z: aed98b20-f67d-4585-a0f5-c61ccd20c908 - LoggerBase.cs: No matching token was found in the cache
LOG: 2018-02-05T20:00:06.5334106Z: aed98b20-f67d-4585-a0f5-c61ccd20c908 - LoggerBase.cs: No matching token was found in the cache
LOG: 2018-02-05T20:00:06.5354172Z: aed98b20-f67d-4585-a0f5-c61ccd20c908 - LoggerBase.cs: Looking up cache for a token...
LOG: 2018-02-05T20:00:06.5374304Z: aed98b20-f67d-4585-a0f5-c61ccd20c908 - LoggerBase.cs: Looking up cache for a token...
LOG: 2018-02-05T20:00:06.5394294Z: aed98b20-f67d-4585-a0f5-c61ccd20c908 - LoggerBase.cs: No matching token was found in the cache
LOG: 2018-02-05T20:00:06.5404297Z: aed98b20-f67d-4585-a0f5-c61ccd20c908 - LoggerBase.cs: No matching token was found in the cache
LOG: 2018-02-05T20:00:06.5424347Z: aed98b20-f67d-4585-a0f5-c61ccd20c908 - LoggerBase.cs: Looking up cache for a token...
LOG: 2018-02-05T20:00:06.5434378Z: aed98b20-f67d-4585-a0f5-c61ccd20c908 - LoggerBase.cs: Looking up cache for a token...
LOG: 2018-02-05T20:00:06.5454447Z: aed98b20-f67d-4585-a0f5-c61ccd20c908 - LoggerBase.cs: No matching token was found in the cache
LOG: 2018-02-05T20:00:06.5464466Z: aed98b20-f67d-4585-a0f5-c61ccd20c908 - LoggerBase.cs: No matching token was found in the cache
LOG: 2018-02-05T20:00:06.5484527Z: aed98b20-f67d-4585-a0f5-c61ccd20c908 - LoggerBase.cs: Looking up cache for a token...
LOG: 2018-02-05T20:00:06.5504596Z: aed98b20-f67d-4585-a0f5-c61ccd20c908 - LoggerBase.cs: Looking up cache for a token...
LOG: 2018-02-05T20:00:06.5514595Z: aed98b20-f67d-4585-a0f5-c61ccd20c908 - LoggerBase.cs: No matching token was found in the cache
LOG: 2018-02-05T20:00:06.5534657Z: aed98b20-f67d-4585-a0f5-c61ccd20c908 - LoggerBase.cs: No matching token was found in the cache
LOG: 2018-02-05T20:00:06.5544727Z: aed98b20-f67d-4585-a0f5-c61ccd20c908 - LoggerBase.cs: Looking up cache for a token...
LOG: 2018-02-05T20:00:06.5564753Z: aed98b20-f67d-4585-a0f5-c61ccd20c908 - LoggerBase.cs: Looking up cache for a token...
LOG: 2018-02-05T20:00:06.5574752Z: aed98b20-f67d-4585-a0f5-c61ccd20c908 - LoggerBase.cs: No matching token was found in the cache
LOG: 2018-02-05T20:00:06.5594841Z: aed98b20-f67d-4585-a0f5-c61ccd20c908 - LoggerBase.cs: No matching token was found in the cache
LOG: 2018-02-05T20:00:06.5604836Z: aed98b20-f67d-4585-a0f5-c61ccd20c908 - LoggerBase.cs: Looking up cache for a token...
LOG: 2018-02-05T20:00:06.5624882Z: aed98b20-f67d-4585-a0f5-c61ccd20c908 - LoggerBase.cs: Looking up cache for a token...
LOG: 2018-02-05T20:00:06.5654985Z: aed98b20-f67d-4585-a0f5-c61ccd20c908 - LoggerBase.cs: No matching token was found in the cache
LOG: 2018-02-05T20:00:06.5675035Z: aed98b20-f67d-4585-a0f5-c61ccd20c908 - LoggerBase.cs: No matching token was found in the cache
LOG: 2018-02-05T20:00:06.6296673Z: aed98b20-f67d-4585-a0f5-c61ccd20c908 - LoggerBase.cs: Exception type: Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException, ErrorCode: authentication_canceled, StatusCode: 0
LOG: 2018-02-05T20:00:06.6326757Z: aed98b20-f67d-4585-a0f5-c61ccd20c908 - LoggerBase.cs: Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException: User canceled authentication

**Comment by jmprieur** [comment]
I suspect that this is the same as https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/969. We are currently working on it
cc: @SomkaPe @jennyf19

**Comment by mores** [comment]
@jmprieur, confirmed that rolling back to 3.17.3 of Microsoft.IdentityModel.Clients.ActiveDirectory fixes this  issue.

**Comment by jmprieur** [comment]
thanks for confirming, @mores. We'll have a fix soon.

**Comment by jmprieur** [comment]
Fix available.
