### ISSUE TITLE
Optional steps required??

### ISSUE THREAD

**Issue by scastria** [Azure-Samples/active-directory-dotnet-native-multitarget#23]
If I perform the optional steps and register the app in my own AAD tenant and change the returnUri and clientId, everything works.  But if I restore the returnUri and clientId to their original values which according to the documentation will still work because it is configured to work with all tenants, it doesn't work.  After I enter my password, I get:

AADSTS50011: The reply url specified in the request does not match the reply urls configured for the application: '8313f713-eaf3-499c-ac75-516592f38d5f'.

I assume that the developers of this sample registered this application in their own AAD tenant and was assigned appId = 8313f713-eaf3-499c-ac75-516592f38d5f.  I assume they specified returnUri of "https://MyDirectorySearcherApp" since that is what is in the sample code as checked in.  I also assume that registering this app in their own AAD tenant somehow makes it work for all tenants??  Perhaps that is what availableToOtherTenants = true means??

So if this is supposed to work for all tenants, why am I getting a bad repy url message?

**Comment by jennyf19** [comment]
@scastria 
We respond faster to customers now...sorry you never got an answer to your question above. We are doing better! 

This sample is now archived, there is a better sample taking advantage of the Microsoft identity platform (formerly Azure AD v2.0)
Check it out: https://github.com/Azure-Samples/active-directory-xamarin-native-v2
