### ISSUE TITLE
get AccessToken for ADFS 3.0 OpenId

### ISSUE THREAD

**Issue by Ajaysinh4377** [Azure-Samples/active-directory-dotnet-native-multitarget#25]
We have any method that returns AccessToken using "Scope" instead of "resource" if no then how can I find resource URL for ADFS 3.0 OpenId connection.

**Comment by jmprieur** [comment]
You probably want to try the Microsoft Identity platform v2.0 (AAD v2.0) samples:
https://aka.ms/aaddevsamplesv2 ?

**Comment by jennyf19** [comment]
@Ajaysinh4377 
This sample is now archived, there is a better sample taking advantage of the Microsoft identity platform (formerly Azure AD v2.0)
Check it out: https://github.com/Azure-Samples/active-directory-xamarin-native-v2
