### ISSUE TITLE
Generate Refresh Token

### ISSUE THREAD

**Issue by Akinnagbe** [Azure-Samples/active-directory-dotnet-native-multitarget#28]
Can this be used to generate a refresh token for a native app e.g Xamarin Forms

**Comment by jmprieur** [comment]
the refresh token is kept in the token cache

**Comment by Akinnagbe** [comment]
@jmprieur,

Thanks a lot for the reply. 
But this is the issue i have.
I need to know when the token expires, i.e. the ExpiresOn property is always set to same datetime when the Token was generated because when the app is loaded or resumed, need to know if the Token is expired or not.

Thanks

**Comment by jmprieur** [comment]
The AuthenticationResult contains the Expiry date, @Akinnagbe. Does this work for you?

**Comment by jennyf19** [comment]
@Akinnagbe 

This sample is now archived, there is a better sample taking advantage of the Microsoft identity platform (formerly Azure AD v2.0)
Check it out: https://github.com/Azure-Samples/active-directory-xamarin-native-v2
