### ISSUE TITLE
ADAL sign in on Android - rotation looses user email provided on sign in 

### ISSUE THREAD

**Issue by dinobu** [Azure-Samples/active-directory-dotnet-native-multitarget#29]
How do you deal with screen orientation issue on Android when user tries to sign in using ADAL ((Microsoft.IdentityModel.Clients.ActiveDirectory))?  What I see is following:

1. In my app user taps on Login on Android
2. User is prompted to enter user email on Microsoft sing in page
3. User enters email and hits Next
4. User is prompted to provide password
5. User rotates device some time during entering the password but before tapping on Sign In button

PROBLEM: If user now rotates Android device, he is returned back to step 2 and the already provided user email is lost.  Rotating device should not return back but just continue where user left off.

**Comment by dinobu** [comment]
If you are also running into issue on Android where device rotation returns you back to prompt for user email, you can follow up progress of fixes for both ADAL and MSAL here:

https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/1622 https://github.com/xamarin/xamarin-android/issues/3326

**Comment by jennyf19** [comment]
@dinobu Fixed in ADAL 5.1.1...need to update this sample, so will leave this issue open until i get around to it. :)

**Comment by negberts** [comment]
Would be nice if this example could be upgraded to Adal 5

**Comment by jennyf19** [comment]
@negberts @dinobu 
This sample is now archived, there is a better sample taking advantage of the Microsoft identity platform (formerly Azure AD v2.0)
Check it out: https://github.com/Azure-Samples/active-directory-xamarin-native-v2

The above issue is fixed in MSAL.
