### ISSUE TITLE
AdalClientException when initializing AuthenticationContext: TeamId returned null from the iOS keychain

### ISSUE THREAD

**Issue by slnali** [Azure-Samples/active-directory-dotnet-native-multitarget#31]
https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/iOS-Keychain-Access followed these instructions to rectify issue but after adding Entitlements.plist to custom entitlements, i now get could not find any provisioning profiles for iOS error? 
![image](https://user-images.githubusercontent.com/9381704/64990608-07f3fc80-d8c8-11e9-937b-52f5446038f2.png)

![image](https://user-images.githubusercontent.com/9381704/64990653-1fcb8080-d8c8-11e9-8d58-d78644f3fa6f.png)

**Comment by jennyf19** [comment]
@slnali you need to have a provisioning profile set up. you can go through the properties of the iOS project to make sure it's set up correctly.

This sample is now archived, there is a better sample taking advantage of the Microsoft identity platform (formerly Azure AD v2.0)
Check it out: https://github.com/Azure-Samples/active-directory-xamarin-native-v2

if you have issues, please tag me here or in the new sample's repo. thanks.
