### ISSUE TITLE
Xamarin.Auth - Could it work with Adal?

### ISSUE THREAD

**Issue by dazinator** [Azure-Samples/active-directory-dotnet-native-multitarget#7]
I've not delved into  [Xamarin.Auth](https://components.xamarin.com/gettingstarted/xamarin.auth) yet, but it looks like it does a very similar type of thing? 

It has the concept of authentication providers though. Would it be a nice idea / possible to write an `Adal provider` for xamarin auth? - just putting it out there

**Comment by jmprieur** [comment]
Closing this issue as external (the request is on the library. I copied it here https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/787)
