### ISSUE TITLE
3.2.204272344-alpha Microsoft.IdentityModel.Clients.ActiveDirectory

### ISSUE THREAD

**Issue by katopotato** [Azure-Samples/active-directory-dotnet-native-multitarget#8]
Anyone else encounter this problem? How should I got about fixing it ... 

Steps to reproduce:
1. Download/Clone project
2. Load into Visual Studio
3. Download missing packages via NuGet
4. Receive error
5. Clicking restore results in same problem occuring
![nugeterror](https://cloud.githubusercontent.com/assets/5599263/7978689/a6b47486-0adb-11e5-864f-e12c674bde47.png)

(Searching for this specific package via Nuget also shows that it does not exist ...)

**Comment by JorgeRi** [comment]
Yes, I get this error too, with VS 2013 Professional and Xamarin Studio

**Comment by blrchen** [comment]
same error here. I am able to get a success build after upgrading to latest alpha package. The one I use is http://www.nuget.org/packages/Microsoft.IdentityModel.Clients.ActiveDirectory/3.4.206191646-alpha

**Comment by dstrockis** [comment]
Hi all - Not sure why that particular version of the library ceased to exist.  I will update the sample to the latest pre-release version shortly (unless one of you guys beats me to it).

For now, do as @blrchen did and update to the latest pre-release package.

**Comment by jgjestad** [comment]
I still get this error.

**Comment by jmprieur** [comment]
Now fixed
