### ISSUE TITLE
AADSTS90014 after entering password on Android

### ISSUE THREAD

**Issue by jamiefraser** [Azure-Samples/active-directory-dotnet-native-multitarget#9]
Hi there,

I'm using this sample, but had an issue with restoring the Nuget packages for ADAL.  Since the sample is supposed to be for a very recent Alpha version of ADAL I installed the newest Alpha package I could find (3.3.206061641-alpha) which may be the source of my troubles.  I've configured my Azure AD with a new native app that I'm using to execute this sample.

When I run the iOS sample, everything goes through as expected -> I enter a user name to search for , I get prompted to login, redirected to my company's login page, permissions are requested and granted and I see the results.  When I run the Android sample, I enter the user name to search for, get prompted to login, redirected to my company's login page and then encounter this exception after entering my password:

AADSTS90014: The request body must contain the following parameter: "client_secret or client_assertion".

I'm not sure what to do to t-shoot this problem.  I found some documentation here:

https://github.com/AzureAD/azure-activedirectory-library-for-android

that suggests I need to add the following permissions to the Android manifest:  ACCESS_NETWORK_STATE,  INTERNET, GET_ACCOUNTS, USE_CREDENTIALS, and MANAGE_ACCOUNTS which I have added.

From what I can see this all looks correct, which likely just means I've skipped some blindingly obvious step.  Thoughts on how I can approach troubleshooting this?

**Comment by jmprieur** [comment]
no longer relevant at this point.
